language: python
sudo: false
cache:
  directories:
  - eggs
  - downloads
python:
  - 2.7
  - 3.5
  - 3.6
matrix:
  fast_finish: true
install:
  - python bootstrap-buildout.py
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout -N buildout:download-cache=downloads
script:
  - bin/test -v
notifications:
    email: false

